name: Gitops-ci

on:
  push:
    branches: 
      - main
  pull_request_review:
    types:
      - submitted

jobs:
  build:
    name: Setup node and auth dockerhub
    runs-on: ubuntu-latest

    outputs:
      output_sha: ${{ steps.sha.outputs.short_sha }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: '>=16'
      
      - name: Get short of git commit hash
        id: sha
        run: |
          git_hash=$(git describe --match 'v[0-9]*' --tags --always)
          echo "::set-output name=short_sha::$git_hash"
      
      - name: Print short commit sha
        run: echo ${{ steps.sha.outputs.short_sha }}
      
      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web:v-${{ steps.sha.outputs.short_sha }}
          push: true
          file: Dockerfile
  
  deploy:
    name: Setup git and deploy to k8s
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: 'RPLGDC-1/infra-web'
          token: ${{ secrets.TOKEN }}
      
      - name: Setup git
        run: |
          git config user.email "yazid.al2418@gmail.com"
          git config user.name "Yazid Al Ghozali"
      
      - name: Update deployment k8s
        env:
          OUTPUT_SHA: ${{ needs.build.outputs.output_sha }}
        run: |
          pwd
          sed -i "s#image: 211104/web:v-.*#image: 211104/web:v-$OUTPUT_SHA#" deployment.yaml
          cat deployment.yaml
      
      - name: Check Working Tree
        run: git status
      
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          OUTPUT_SHA: ${{ needs.build.outputs.output_sha}}
        with:
          commit_message: "Update image with version: v-$OUTPUT_SHA"
