name: Gitops-ci

on:
  push:
    branches: 
      - feature/github-actions

jobs:
  build:
    name: Setup node and auth dockerhub
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: '>=16'
      
      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          tags: ${{secrets.DOCKERHUB_USERNAME}}/web:v0.0.${{ github.run_number }}
          push: true
          file: Dockerfile
  
  deploy:
    name: Setup git and deploy to k8s
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: 'RPLGDC-1/frontend'
          token: ${{ secrets.TOKEN }}
      
      - name: Setup git
        run: |
          git config user.email "yazid.al2418@gmail.com"
          git config user.name "Yazid Al Ghozali"
      
      - name: Update deployment k8s
        run: |
          pwd
          cd ./deployments
          ls
          cat deployment.yaml
          sed -i 's|image: 211104/web:v0.0.2|image: 211104/web:v0.0.${{github.run_number}}|' deployment.yaml
          cat deployment.yaml
      
      - name: Commit changes
        run: |
          git status
          git add .
          git commit -m "Apply latest deployment with manifest: v${{github.run_number}}"
          git push origin main